# Generated by Django 5.0.6 on 2024-06-19 15:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
